title: Lawrence's Personal Projects
author: Lawrence Lin
logo: 'my_logo.png'

# Short description about my website
description: >-
    A brief introduction to my personal projects and work experience.


